### ISSUE TITLE
The code is incompatible with the current version of expo SDK

### ISSUE THREAD

**Issue by vamsikeshwaran** [Movelytics/ReactNativeWebcamDemo#1]
<img width="313" alt="Screenshot 2024-10-29 at 8 57 28 PM" src="https://github.com/user-attachments/assets/c5fb3048-fa94-4f5c-97b6-3b07cd5dff17">

**Comment by sepretf** [comment]
hello @vamsikeshwaran ! Thanks for reporting this issue 🙏 !
The code has been updated and is now compatible with the latest version of Expo SDK 51.
